name: Test

on:
  pull_request:
  push:
    branches: [main]

defaults:
  run:
    working-directory: extension

# Environment variables are imported, but tests mock the actual values, so these are placeholders
env:
  MUCKROCK_DOCUMENTCLOUD_API: https://api.dev.documentcloud.org/api/
  MUCKROCK_KLAXON_ID: "999"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: extension/package-lock.json

      - name: Install
        run: npm ci

      - name: Check
        run: npm run check

      - name: Test
        run: npm test
